name: Get Flight Data

on:
  schedule:
    - cron: '0 0 * * 5' # Runs at midnight on friday
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install .

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Run Python Script
      run: |
        python src/get_flight_data.py \
          --max-total-calls 1000 \
          --bucket gpt-travel-planner-data \
          --output-file-basename flights.pickle
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DUFFEL_API_KEY: ${{ secrets.DUFFEL_API_KEY }}
        FLIGHT_RADAR_EMAIL: ${{ vars.FLIGHT_RADAR_EMAIL }}
        FLIGHT_RADAR_PASSWORD: ${{ secrets.FLIGHT_RADAR_PASSWORD }}
        AVIATIONSTACK_API_KEY: ${{ secrets.AVIATIONSTACK_API_KEY }}
        AVIATIONSTACK_API_KEY2: ${{ secrets.AVIATIONSTACK_API_KEY2 }}
